# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/gcapo/Documents/CESE/05_MyS/TF/senial_seno_ila/senial_seno_ila.srcs/sources_1/bd/sistema/ip/sistema_auto_pc_0/sistema_auto_pc_0.xci
# IP: The module: 'sistema_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gcapo/Documents/CESE/05_MyS/TF/senial_seno_ila/senial_seno_ila.srcs/sources_1/bd/sistema/ip/sistema_auto_pc_0/sistema_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/gcapo/Documents/CESE/05_MyS/TF/senial_seno_ila/senial_seno_ila.srcs/sources_1/bd/sistema/ip/sistema_auto_pc_0/sistema_auto_pc_0.xci
# IP: The module: 'sistema_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/gcapo/Documents/CESE/05_MyS/TF/senial_seno_ila/senial_seno_ila.srcs/sources_1/bd/sistema/ip/sistema_auto_pc_0/sistema_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sistema_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
